name: ci

on:
  push:
    branches:
      - 'helium/hotspot'
jobs:
  #Using this action https://github.com/marketplace/actions/build-and-push-docker-images
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
        with:
          ref: helium/hotspot
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${GITHUB_REPOSITORY}:latest
            ${GITHUB_REPOSITORY}:0.0.1
            ghcr.io/${GITHUB_REPOSITORY}:latest
            ghcr.io/${GITHUB_REPOSITORY}:0.0.1